---
AllCops:
  Exclude:
    - 'build/**/*'

Metrics/AbcSize:
  Max: 65

Metrics/ParameterLists:
  Max: 8

Metrics/LineLength:
  Max: 120

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# This is just so we don't have to correct a zillion lines
Style/StringLiterals:
  Enabled: false

# XXX ruby 1.8 compatibility
# Ruby 1.8 does't have each_with_object()
Style/EachWithObject:
  Enabled: false

# Ruby 1.8 requirement
Style/DotPosition:
  EnforcedStyle: trailing

# Ruby 1.8 requirement
Style/Lambda:
  Enabled: false

# Ruby 1.8 requirement
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# in ruby1.8, proc {} is a synonym for lambda {}
# in ruby1.9, proc {} is a synonym for Proc.new {}
Style/Proc:
  Enabled: false

# This configuration was generated by `rubocop --auto-gen-config`
# on 2015-02-17 21:13:39 +0000 using RuboCop version 0.29.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

Style/TrivialAccessors:
  Enabled: false
