---
AllCops:
  Exclude:
    - 'build/**/*'

Metrics/AbcSize:
  Max: 65

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 45

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ModuleLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals: # This is just so we don't have to correct a zillion lines
  Enabled: false

### XXX ruby 1.8 compatibility
# Ruby 1.8 does't have each_with_object()
Style/EachWithObject:
  Enabled: false

# Ruby 1.8 requirement
Style/DotPosition:
  EnforcedStyle: trailing

# Ruby 1.8 requirement
Style/Lambda:
  Enabled: false

# Ruby 1.8 requirement
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# in ruby1.8, proc {} is a synonym for lambda {}
# in ruby1.9, proc {} is a synonym for Proc.new {}
Style/Proc:
  Enabled: false

# flat_map not present in ruby1.8
Performance/FlatMap:
  Enabled: false
