---
AllCops:
  Exclude:
    - 'build/**/*'

Metrics/AbcSize:
  Max: 65

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 45

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EachWithObject: # this is just confusing
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals: # This is just so we don't have to correct a zillion lines
  Enabled: false
