#!/bin/sh

echo -n "Running rake spec: "
SPEC_OUTPUT=`rake spec 2>&1`
if [ $? -ne 0 ]; then
	echo "[31mFAIL[0m" >&2
	echo "$SPEC_OUTPUT" >&2
	exit 1
else
	echo "[32mOK[0m"
fi

if which rubocop > /dev/null; then
	# rake lint is configured to work with Jenkins
	# here we run rubocop with no arguments for interactive use
	rubocop || exit 1
else
	echo "[31mrubocop not found[0m" >&2
	exit 1
fi
